/* the controller class process the user interactions with the gui
*by processing the press events on the numbers and operators 
*/
package com.javacademy.calc;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.text.Text;

public class CalcController {
	@FXML
	private Text output;

	private long number1 = 0;
	private String operator = "";
	private boolean start = true;
	private long result = 0;
	private String oprand = ""; 

	private CalcModel model = new CalcModel();

	/*
	 * the method for the event generated by the number buttons first check if the
	 * screen empty or not second get the text on the button and save it on a
	 * variable value third show the text on the button pressed appended to the text
	 * on the screen this method works only with numbers buttons
	 */
	@FXML
	private void processNumpad(ActionEvent event) {

		if (start) { // to check if there any thing on the screen clean it
			output.setText("");
			start = false;
		}

		String value = ((Button) event.getSource()).getText(); // to get the number on the button
		output.setText(output.getText() + value); // to show the number on the screen and append it to the previous
													// showed number
	}

	/*the method for doing the calculation and showing the result
	 * first the text on the operator button saved to variable value
	 * second test if the operator is not the equal sign 
	 * if its not and the variable operator is empty save the text on the button to variable operator
	 * then save the number shown on the screen to a variable number1 and clear the screen
	 * after equal sign get pressed call the method calculate of the class CalcModel 
     */
	@FXML
	private void processOperator(ActionEvent event) {
		String value = ((Button) event.getSource()).getText(); // to get the operator

		if (!"=".equals(value)) { // checking if the operator is the equal sign
			if (!operator.isEmpty()) // checking if the operator is empty
				return;

			operator = value; // if the operator variable empty put value into it
			number1 = Long.parseLong(output.getText()); // to set number1 with the contents of the screen
			output.setText(""); // then clear the screen

		} // in the end of this part we have operator holding the sign and number1 holding
			// the number on the screen
		else { // if the user clicked on the = sign
			if (operator.isEmpty())
				return;
			
			
			//the following line is to do the calculation and saving the result in int data type
			result = model.calculate(number1, Long.parseLong(output.getText()), operator);
			oprand = output.getText();// to save the current screen contents
			output.setText("");//clear the screen before showing the complete operation  
			//the following line is to show the complete operation with its result on the screen 
       
			output.setText(String.valueOf(number1)+operator+oprand+"="+String.valueOf(result));
			operator = ""; // clear operator variable
			start = true; // set the start flag
		}
	}

	@FXML
	private void clear(ActionEvent event) {
		output.setText("");
		number1 = 0;

	}

}
