package com.javacademy.calc;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.text.Text;

public class CalcController {
	@FXML
    private Text output;

    private long number1 = 0;
    private String operator = "";
    private boolean start = true;

    private Model model = new Model();
    //the method for the event generated by the number buttons
    @FXML
    private void processNumpad(ActionEvent event) {
        if (start) {             // to check if there any thing on the screen clean it
            output.setText("");
            start = false;
        }

        String value = ((Button)event.getSource()).getText(); // to get the number on the button 
        output.setText(output.getText() + value);  // to show the number on the screen and append it to the previous showed number
    }
    
    //the method for doing the calculation and showing the result
    @FXML
    private void processOperator(ActionEvent event) {
        String value = ((Button)event.getSource()).getText(); //to get the operator 

        if (!"=".equals(value)) { //checking if the operator is the equal sign
            if (!operator.isEmpty()) // checking if the operator is empty
                return;

            operator = value;    // if the operator variable empty put value into it
            number1 = Long.parseLong(output.getText()); //to set number1 with the contents of the screen 
            output.setText(""); // then clear the screen
        }    // in the end of this part we have operator holding the sign and number1 holding the number on the screen
        else { // if the user clicked on the = sign
            if (operator.isEmpty())
                return;

            output.setText(String.valueOf(model.calculate(number1, Long.parseLong(output.getText()), operator)));//to do the calculation and showing the result
            operator = ""; //clear operator variable
            start = true; // set the start flag 
        }
    }
    
    @FXML
    private void clear(ActionEvent event){
    	 output.setText("");
    	 number1 = 0;
    	
    }
    

}
